services:
  mysql:
    image: mysql:8.0
    container_name: leonardo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $${MYSQL_ROOT_PASSWORD:"SenaSoft2024@Leonardo"}
      MYSQL_DATABASE: leonardo_senasoft
      MYSQL_USER: $${DB_USERNAME:leonardo_user}
      MYSQL_PASSWORD: $${DB_PASSWORD:"L30n4rd0_S3n4S0ft_2024"}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - leonardo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  leonardo-app:
    build:
      context: ../../../
      dockerfile: Dockerfile
    container_name: leonardo-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://mysql:3306/leonardo_senasoft?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
      DB_USERNAME: $${DB_USERNAME:leonardo_user}
      DB_PASSWORD: $${DB_PASSWORD:"L30n4rd0_S3n4S0ft_2024"}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - leonardo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  leonardo-network:
    driver: bridge

volumes:
  mysql_data:
